In [2]:
import scipy
import matplotlib as mpl
import pandas as pd

zeros = pd.read_csv('./Quarter/zed.csv')
ones = pd.read_csv('./Quarter/nyc.csv')
q = pd.read_csv('StreetScoreNYC-Aggregated.csv')

q

             avg  gridID
0      22.279450     196
1      17.950998     197
2      21.120518     198
3      22.734419     199
4      23.235004     200
5      18.710251     201
6      22.085176     202
7      20.430030     203
8      21.608192     204
9      20.098252     205
10     20.083464     206
11     26.821541     207
12     20.884911     208
13     20.499053     209
14     22.762152     210
15     23.123714     215
16     29.468908     216
17     20.943741     426
18     20.505839     427
19     17.873001     428
20     19.557288     429
21     20.052414     430
22     18.368172     431
23     21.413067     432
24     23.169758     433
25     24.908276     434
26     19.140865     435
27     21.811961     436
28     19.663059     437
29     19.538692     438
...          ...     ...
19474  25.615719   53746
19475  28.737615   53747
19476  29.398931   53748
19477  22.200115   53749
19478  25.460827   53750
19479  25.844656   53751
19480  26.589759   53752
19481  23.994577   53753
19482  27.966408   53754
19483  25.279336   53755
19484  26.719218   53966
19485  20.653399   53967
19486  24.477936   53968
19487  24.741840   53969
19488  24.687616   53970
19489  25.241251   53971
19490  26.507545   53972
19491  23.749257   53973
19492  22.082750   53974
19493  25.810196   53975
19494  30.502871   53976
19495  33.106403   53977
19496  33.234264   53978
19497  22.854542   54195
19498  27.912496   54196
19499  24.489921   54197
19500  26.858607   54198
19501  24.078130   54199
19502  24.630159   54200
19503  24.975813   54201

[19504 rows x 2 columns]

In [5]:
df14 = ones.drop(ones[ones.year != 2014].index)

df14.max()

geoId                 36085032300
gridID                      57369
day_name                Wednesday
month_name                    Sep
date                  9/9/14 9:58
year                         2014
hour                            4
lat                       40.9055
lon                      -73.7052
tempf                       91.94
vis                            10
num_establishments            200
num_liquor_stores               6
num_restaurants                66
num_stores                    200
num_bars                       32
expected                        2
dtype: object

In [7]:
ones

,geoId,gridID,day_name,month_name,date,year,hour,lat,lon,tempf,vis,num_establishments,num_liquor_stores,num_restaurants,num_stores,num_bars,expected
0,36047028100,29233,Sunday,Jan,1/1/06 0:01,2006,1,40.693350,-73.938089,32.00,10.0,11,0,0,2,0,1
1,36005042500,36209,Sunday,Jan,1/1/06 0:10,2006,1,40.869713,-73.879388,32.00,10.0,14,0,1,4,0,1
2,36005039500,33933,Sunday,Jan,1/1/06 0:55,2006,1,40.849663,-73.898324,32.00,10.0,22,0,0,11,0,1
3,36047042900,31288,Sunday,Jan,1/1/06 2:25,2006,1,40.701964,-73.921047,32.00,9.0,29,0,0,8,0,1
4,36081028300,35607,Sunday,Jan,1/1/06 2:30,2006,1,40.747886,-73.885068,32.00,9.0,198,0,17,48,5,1
5,36047117400,36337,Sunday,Jan,1/1/06 2:30,2006,1,40.686171,-73.879388,32.00,9.0,7,0,0,1,0,1
6,36061027900,30035,Sunday,Jan,1/1/06 2:30,2006,1,40.856824,-73.930515,32.00,9.0,15,0,0,4,0,1
7,36061004100,22344,Sunday,Jan,1/1/06 3:00,2006,1,40.720623,-73.994898,32.00,9.0,199,1,28,66,10,1
8,36047029900,30617,Sunday,Jan,1/1/06 3:00,2006,1,40.678991,-73.926728,32.00,9.0,41,0,0,8,0,1
9,36005022300,31878,Sunday,Jan,1/1/06 3:00,2006,1,40.841068,-73.915366,32.00,9.0,29,0,1,7,2,1
10,36061003800,22798,Sunday,Jan,1/1/06 3:15,2006,1,40.726364,-73.991111,32.00,9.0,174,0,22,31,17,1
11,36061020102,27094,Sunday,Jan,1/1/06 4:00,2006,1,40.805244,-73.955132,32.00,10.0,106,1,11,19,3,1
12,36005013300,33494,Sunday,Jan,1/1/06 4:10,2006,1,40.822442,-73.902111,32.00,10.0,33,0,2,6,0,1
13,36047026900,28784,Sunday,Jan,1/1/06 4:15,2006,1,40.680427,-73.941877,32.00,10.0,93,0,7,22,1,1
14,36047027300,29013,Sunday,Jan,1/1/06 4:20,2006,1,40.680427,-73.939983,32.00,10.0,83,1,8,13,1,1
15,36061018000,29164,Sunday,Jan,1/1/06 4:30,2006,1,40.792343,-73.938089,32.00,10.0,45,0,0,6,0,1
16,36061002601,24175,Sunday,Jan,1/1/06 4:45,2006,1,40.722059,-73.979749,32.00,10.0,94,0,3,8,1,1
17,36047087200,29491,Sunday,Jan,1/1/06 5:00,2006,1,40.651700,-73.936196,33.08,10.0,55,1,2,13,1,1
18,36047036100,31768,Sunday,Jan,1/1/06 5:00,2006,1,40.670374,-73.917260,33.08,10.0,23,0,0,5,0,1
19,36061022800,28232,Sunday,Jan,1/1/06 5:30,2006,1,40.815277,-73.945664,33.08,10.0,76,0,4,7,0,1
20,36047024700,27639,Sunday,Jan,1/1/06 5:45,2006,1,40.680427,-73.951345,33.08,10.0,92,0,5,47,0,1
21,36047093200,30188,Sunday,Jan,1/1/06 6:00,2006,1,40.637332,-73.930515,33.98,10.0,20,0,0,6,0,1
22,36081046200,47314,Sunday,Jan,1/1/06 6:00,2006,1,40.707706,-73.788494,33.98,10.0,98,1,9,26,1,1
23,36061019600,29156,Sunday,Jan,1/1/06 7:10,2006,2,40.803811,-73.938089,33.98,8.0,70,1,1,23,0,1
24,36081018200,45963,Sunday,Jan,1/1/06 7:20,2006,2,40.674682,-73.799856,33.98,8.0,47,1,3,10,0,1
25,36047039300,30378,Sunday,Jan,1/1/06 8:45,2006,2,40.693350,-73.928621,35.06,9.0,54,1,6,15,0,1
26,36005001600,38990,Sunday,Jan,1/1/06 10:30,2006,2,40.822442,-73.856664,37.94,10.0,29,0,0,4,0,1
27,36061022400,28236,Sunday,Jan,1/1/06 10:45,2006,2,40.809544,-73.945664,37.94,10.0,91,0,3,3,3,1
28,36047098600,34304,Sunday,Jan,1/1/06 13:20,2006,3,40.645953,-73.896430,41.00,10.0,24,0,0,6,0,1
29,36061013300,23458,Sunday,Jan,1/1/06 13:30,2006,3,40.765099,-73.985430,41.00,10.0,153,1,4,17,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191211,36005025300,33237,Thursday,Dec,12/31/15 3:00,2015,1,40.862553,-73.904005,44.96,9.0,79,2,3,34,0,1
191212,36005007000,37839,Thursday,Dec,12/31/15 3:07,2015,1,40.831039,-73.866132,44.96,9.0,43,1,8,12,2,1
191213,36005023000,37597,Thursday,Dec,12/31/15 3:30,2015,1,40.849663,-73.868026,44.96,9.0,24,0,0,4,0,1
191214,36061009300,21409,Thursday,Dec,12/31/15 4:00,2015,1,40.747886,-74.002472,44.96,7.0,200,0,7,13,3,1
191215,36047026200,21957,Thursday,Dec,12/31/15 4:45,2015,1,40.618649,-73.998685,44.96,7.0,27,1,3,5,0,1
191216,36047069601,32029,Thursday,Dec,12/31/15 5:40,2015,1,40.624398,-73.915366,46.04,10.0,15,0,0,3,0,1
191217,36005023501,33016,Thursday,Dec,12/31/15 6:00,2015,1,40.851095,-73.905898,46.04,10.0,53,0,1,8,0,1
191218,36081000700,28050,Thursday,Dec,12/31/15 6:10,2015,1,40.747886,-73.947558,46.04,10.0,38,0,4,10,0,1
191219,36047037900,31531,Thursday,Dec,12/31/15 7:10,2015,2,40.681863,-73.919153,46.94,9.0,22,0,1,4,0,1
191220,36047073000,30425,Thursday,Dec,12/31/15 7:50,2015,2,40.625835,-73.928621,46.94,9.0,35,0,3,11,1,1
191221,36081019400,45727,Thursday,Dec,12/31/15 8:00,2015,2,40.684735,-73.801750,46.94,10.0,8,0,0,0,0,1
191222,36005037400,37579,Thursday,Dec,12/31/15 9:35,2015,2,40.875441,-73.868026,46.94,10.0,26,0,0,4,0,1
191223,36061028500,30261,Thursday,Dec,12/31/15 11:10,2015,2,40.861121,-73.928621,46.94,10.0,47,0,4,8,0,1
191224,36047105804,35905,Thursday,Dec,12/31/15 11:30,2015,2,40.648827,-73.883175,46.94,10.0,15,0,0,1,0,1
191225,36081056500,34041,Thursday,Dec,12/31/15 11:50,2015,2,40.694786,-73.898324,46.94,10.0,18,0,0,9,0,1
191226,36061018900,25954,Thursday,Dec,12/31/15 12:10,2015,2,40.798077,-73.964600,46.94,10.0,59,0,5,16,1,1
191227,36061009700,21867,Thursday,Dec,12/31/15 13:30,2015,3,40.747886,-73.998685,46.94,10.0,33,0,1,1,0,1
191228,36047037100,32449,Thursday,Dec,12/31/15 14:20,2015,3,40.678991,-73.911579,48.02,10.0,44,1,3,8,0,1
191229,36061017800,29849,Thursday,Dec,12/31/15 14:50,2015,3,40.795210,-73.932409,48.02,10.0,44,1,3,10,1,1
191230,36005017300,31888,Thursday,Dec,12/31/15 15:40,2015,3,40.826741,-73.915366,46.94,10.0,12,0,0,2,0,1
191231,36061023300,27765,Thursday,Dec,12/31/15 16:21,2015,3,40.828174,-73.949451,46.04,10.0,103,2,8,26,3,1
191232,36081028700,34918,Thursday,Dec,12/31/15 16:50,2015,3,40.750755,-73.890749,46.04,10.0,45,0,0,0,0,1
191233,36047037900,31304,Thursday,Dec,12/31/15 17:30,2015,3,40.678991,-73.921047,46.04,10.0,65,0,3,18,1,1
191234,36081086400,42526,Thursday,Dec,12/31/15 18:15,2015,3,40.677555,-73.828260,44.96,10.0,20,0,2,6,0,1
191235,36047048400,25380,Thursday,Dec,12/31/15 18:45,2015,3,40.635895,-73.970281,44.96,10.0,28,0,0,1,0,1
191236,36047102400,34542,Thursday,Dec,12/31/15 19:07,2015,4,40.633021,-73.894537,44.96,10.0,12,0,0,3,0,1
191237,36005002000,37620,Thursday,Dec,12/31/15 19:25,2015,4,40.816710,-73.868026,44.96,10.0,4,0,0,2,0,1
191238,36047038100,31075,Thursday,Dec,12/31/15 22:15,2015,4,40.678991,-73.922941,42.08,10.0,54,0,5,11,0,1
191239,36047002200,19191,Thursday,Dec,12/31/15 22:20,2015,4,40.644516,-74.021408,42.08,10.0,33,0,2,6,0,1
191240,36081044400,48001,Thursday,Dec,12/31/15 23:00,2015,4,40.707706,-73.782814,42.08,10.0,45,0,2,16,1,1

In [8]:
d14 = {}

for i, r in df14.iterrows():
    if r['gridID'] not in d14:
        d14[r['gridID']] = { 'gridID': r['gridID'], 'expected': r['expected'] }
    else:
        val = d14[r['gridID']]['expected']
        d14[r['gridID']]['expected'] = val + r['expected']
        
d14

{32768: {'expected': 3, 'gridID': 32768},
 32769: {'expected': 4, 'gridID': 32769},
 32771: {'expected': 2, 'gridID': 32771},
 32774: {'expected': 1, 'gridID': 32774},
 32775: {'expected': 1, 'gridID': 32775},
 32778: {'expected': 1, 'gridID': 32778},
 32780: {'expected': 2, 'gridID': 32780},
 32782: {'expected': 2, 'gridID': 32782},
 32783: {'expected': 2, 'gridID': 32783},
 32785: {'expected': 6, 'gridID': 32785},
 32786: {'expected': 6, 'gridID': 32786},
 32787: {'expected': 3, 'gridID': 32787},
 32788: {'expected': 1, 'gridID': 32788},
 32789: {'expected': 5, 'gridID': 32789},
 32790: {'expected': 2, 'gridID': 32790},
 32792: {'expected': 4, 'gridID': 32792},
 32797: {'expected': 9, 'gridID': 32797},
 32798: {'expected': 3, 'gridID': 32798},
 32799: {'expected': 3, 'gridID': 32799},
 32800: {'expected': 1, 'gridID': 32800},
 32801: {'expected': 2, 'gridID': 32801},
 32802: {'expected': 1, 'gridID': 32802},
 32803: {'expected': 2, 'gridID': 32803},
 32804: {'expected': 1, 'gridID': 32804},
 32805: {'expected': 5, 'gridID': 32805},
 32806: {'expected': 1, 'gridID': 32806},
 32807: {'expected': 1, 'gridID': 32807},
 32808: {'expected': 3, 'gridID': 32808},
 32809: {'expected': 3, 'gridID': 32809},
 32810: {'expected': 2, 'gridID': 32810},
 32811: {'expected': 9, 'gridID': 32811},
 32812: {'expected': 3, 'gridID': 32812},
 32813: {'expected': 1, 'gridID': 32813},
 32814: {'expected': 4, 'gridID': 32814},
 32815: {'expected': 3, 'gridID': 32815},
 32816: {'expected': 3, 'gridID': 32816},
 32817: {'expected': 3, 'gridID': 32817},
 32818: {'expected': 1, 'gridID': 32818},
 32820: {'expected': 1, 'gridID': 32820},
 32838: {'expected': 1, 'gridID': 32838},
 32839: {'expected': 1, 'gridID': 32839},
 32841: {'expected': 1, 'gridID': 32841},
 32842: {'expected': 1, 'gridID': 32842},
 32847: {'expected': 1, 'gridID': 32847},
 32850: {'expected': 1, 'gridID': 32850},
 32853: {'expected': 8, 'gridID': 32853},
 32854: {'expected': 1, 'gridID': 32854},
 32855: {'expected': 4, 'gridID': 32855},
 32857: {'expected': 1, 'gridID': 32857},
 32861: {'expected': 1, 'gridID': 32861},
 32862: {'expected': 1, 'gridID': 32862},
 32885: {'expected': 2, 'gridID': 32885},
 32886: {'expected': 1, 'gridID': 32886},
 32888: {'expected': 1, 'gridID': 32888},
 32890: {'expected': 2, 'gridID': 32890},
 32891: {'expected': 3, 'gridID': 32891},
 32892: {'expected': 1, 'gridID': 32892},
 32893: {'expected': 2, 'gridID': 32893},
 32894: {'expected': 1, 'gridID': 32894},
 32896: {'expected': 2, 'gridID': 32896},
 32897: {'expected': 1, 'gridID': 32897},
 32899: {'expected': 1, 'gridID': 32899},
 32900: {'expected': 1, 'gridID': 32900},
 32901: {'expected': 1, 'gridID': 32901},
 32902: {'expected': 1, 'gridID': 32902},
 32904: {'expected': 3, 'gridID': 32904},
 32905: {'expected': 1, 'gridID': 32905},
 32906: {'expected': 2, 'gridID': 32906},
 32907: {'expected': 3, 'gridID': 32907},
 32908: {'expected': 3, 'gridID': 32908},
 32909: {'expected': 2, 'gridID': 32909},
 32910: {'expected': 3, 'gridID': 32910},
 32911: {'expected': 4, 'gridID': 32911},
 32912: {'expected': 3, 'gridID': 32912},
 32913: {'expected': 3, 'gridID': 32913},
 32915: {'expected': 4, 'gridID': 32915},
 32916: {'expected': 2, 'gridID': 32916},
 32917: {'expected': 5, 'gridID': 32917},
 32918: {'expected': 3, 'gridID': 32918},
 32919: {'expected': 4, 'gridID': 32919},
 32920: {'expected': 5, 'gridID': 32920},
 32921: {'expected': 2, 'gridID': 32921},
 32922: {'expected': 4, 'gridID': 32922},
 32923: {'expected': 1, 'gridID': 32923},
 32924: {'expected': 2, 'gridID': 32924},
 32926: {'expected': 1, 'gridID': 32926},
 32929: {'expected': 3, 'gridID': 32929},
 32931: {'expected': 1, 'gridID': 32931},
 32932: {'expected': 1, 'gridID': 32932},
 32933: {'expected': 1, 'gridID': 32933},
 32935: {'expected': 1, 'gridID': 32935},
 32937: {'expected': 1, 'gridID': 32937},
 32938: {'expected': 1, 'gridID': 32938},
 32957: {'expected': 1, 'gridID': 32957},
 32981: {'expected': 1, 'gridID': 32981},
 32991: {'expected': 1, 'gridID': 32991},
 32993: {'expected': 1, 'gridID': 32993},
 32995: {'expected': 1, 'gridID': 32995},
 32997: {'expected': 2, 'gridID': 32997},
 32998: {'expected': 2, 'gridID': 32998},
 32999: {'expected': 6, 'gridID': 32999},
 33000: {'expected': 1, 'gridID': 33000},
 33001: {'expected': 4, 'gridID': 33001},
 33002: {'expected': 1, 'gridID': 33002},
 33003: {'expected': 5, 'gridID': 33003},
 33006: {'expected': 1, 'gridID': 33006},
 33008: {'expected': 2, 'gridID': 33008},
 33009: {'expected': 5, 'gridID': 33009},
 33010: {'expected': 4, 'gridID': 33010},
 33011: {'expected': 4, 'gridID': 33011},
 33012: {'expected': 2, 'gridID': 33012},
 33013: {'expected': 2, 'gridID': 33013},
 33014: {'expected': 2, 'gridID': 33014},
 33015: {'expected': 2, 'gridID': 33015},
 33016: {'expected': 1, 'gridID': 33016},
 33017: {'expected': 6, 'gridID': 33017},
 33018: {'expected': 1, 'gridID': 33018},
 33019: {'expected': 2, 'gridID': 33019},
 33020: {'expected': 1, 'gridID': 33020},
 33021: {'expected': 5, 'gridID': 33021},
 33022: {'expected': 2, 'gridID': 33022},
 33024: {'expected': 5, 'gridID': 33024},
 33025: {'expected': 1, 'gridID': 33025},
 33026: {'expected': 3, 'gridID': 33026},
 33027: {'expected': 3, 'gridID': 33027},
 33028: {'expected': 1, 'gridID': 33028},
 33029: {'expected': 4, 'gridID': 33029},
 33030: {'expected': 2, 'gridID': 33030},
 33031: {'expected': 7, 'gridID': 33031},
 33032: {'expected': 1, 'gridID': 33032},
 33033: {'expected': 2, 'gridID': 33033},
 33034: {'expected': 1, 'gridID': 33034},
 33035: {'expected': 1, 'gridID': 33035},
 33036: {'expected': 2, 'gridID': 33036},
 33037: {'expected': 2, 'gridID': 33037},
 33038: {'expected': 2, 'gridID': 33038},
 33039: {'expected': 3, 'gridID': 33039},
 33040: {'expected': 8, 'gridID': 33040},
 33041: {'expected': 2, 'gridID': 33041},
 33043: {'expected': 4, 'gridID': 33043},
 54660: {'expected': 1, 'gridID': 54660},
 33080: {'expected': 1, 'gridID': 33080},
 33082: {'expected': 1, 'gridID': 33082},
 33084: {'expected': 1, 'gridID': 33084},
 33090: {'expected': 1, 'gridID': 33090},
 33091: {'expected': 1, 'gridID': 33091},
 33094: {'expected': 1, 'gridID': 33094},
 33115: {'expected': 1, 'gridID': 33115},
 33117: {'expected': 3, 'gridID': 33117},
 33119: {'expected': 2, 'gridID': 33119},
 33120: {'expected': 3, 'gridID': 33120},
 33121: {'expected': 4, 'gridID': 33121},
 33123: {'expected': 1, 'gridID': 33123},
 33124: {'expected': 2, 'gridID': 33124},
 33125: {'expected': 2, 'gridID': 33125},
 33126: {'expected': 4, 'gridID': 33126},
 33127: {'expected': 2, 'gridID': 33127},
 33129: {'expected': 4, 'gridID': 33129},
 33130: {'expected': 2, 'gridID': 33130},
 33134: {'expected': 2, 'gridID': 33134},
 33136: {'expected': 4, 'gridID': 33136},
 33137: {'expected': 6, 'gridID': 33137},
 33138: {'expected': 2, 'gridID': 33138},
 33139: {'expected': 2, 'gridID': 33139},
 33142: {'expected': 9, 'gridID': 33142},
 33143: {'expected': 9, 'gridID': 33143},
 33144: {'expected': 3, 'gridID': 33144},
 33145: {'expected': 2, 'gridID': 33145},
 33146: {'expected': 2, 'gridID': 33146},
 33147: {'expected': 3, 'gridID': 33147},
 33148: {'expected': 2, 'gridID': 33148},
 33150: {'expected': 3, 'gridID': 33150},
 33152: {'expected': 2, 'gridID': 33152},
 33161: {'expected': 4, 'gridID': 33161},
 33163: {'expected': 1, 'gridID': 33163},
 33167: {'expected': 1, 'gridID': 33167},
 33170: {'expected': 1, 'gridID': 33170},
 33207: {'expected': 1, 'gridID': 33207},
 33218: {'expected': 1, 'gridID': 33218},
 33219: {'expected': 1, 'gridID': 33219},
 33220: {'expected': 1, 'gridID': 33220},
 33222: {'expected': 1, 'gridID': 33222},
 33223: {'expected': 1, 'gridID': 33223},
 33226: {'expected': 1, 'gridID': 33226},
 33227: {'expected': 1, 'gridID': 33227},
 33229: {'expected': 2, 'gridID': 33229},
 33230: {'expected': 1, 'gridID': 33230},
 33231: {'expected': 2, 'gridID': 33231},
 33232: {'expected': 3, 'gridID': 33232},
 33235: {'expected': 1, 'gridID': 33235},
 33236: {'expected': 1, 'gridID': 33236},
 33237: {'expected': 7, 'gridID': 33237},
 33238: {'expected': 2, 'gridID': 33238},
 33239: {'expected': 2, 'gridID': 33239},
 33240: {'expected': 14, 'gridID': 33240},
 33241: {'expected': 1, 'gridID': 33241},
 33242: {'expected': 3, 'gridID': 33242},
 33243: {'expected': 1, 'gridID': 33243},
 33244: {'expected': 5, 'gridID': 33244},
 33246: {'expected': 2, 'gridID': 33246},
 33247: {'expected': 3, 'gridID': 33247},
 33248: {'expected': 1, 'gridID': 33248},
 33249: {'expected': 1, 'gridID': 33249},
 33251: {'expected': 2, 'gridID': 33251},
 33252: {'expected': 3, 'gridID': 33252},
 33254: {'expected': 1, 'gridID': 33254},
 33255: {'expected': 5, 'gridID': 33255},
 33256: {'expected': 4, 'gridID': 33256},
 33257: {'expected': 2, 'gridID': 33257},
 33258: {'expected': 7, 'gridID': 33258},
 33259: {'expected': 4, 'gridID': 33259},
 33261: {'expected': 2, 'gridID': 33261},
 33262: {'expected': 1, 'gridID': 33262},
 33263: {'expected': 2, 'gridID': 33263},
 33265: {'expected': 3, 'gridID': 33265},
 33266: {'expected': 5, 'gridID': 33266},
 33267: {'expected': 2, 'gridID': 33267},
 33268: {'expected': 3, 'gridID': 33268},
 33269: {'expected': 1, 'gridID': 33269},
 33270: {'expected': 7, 'gridID': 33270},
 33271: {'expected': 2, 'gridID': 33271},
 33272: {'expected': 5, 'gridID': 33272},
 33306: {'expected': 1, 'gridID': 33306},
 33310: {'expected': 1, 'gridID': 33310},
 33319: {'expected': 2, 'gridID': 33319},
 33320: {'expected': 2, 'gridID': 33320},
 33322: {'expected': 1, 'gridID': 33322},
 33330: {'expected': 1, 'gridID': 33330},
 33341: {'expected': 1, 'gridID': 33341},
 33343: {'expected': 2, 'gridID': 33343},
 33344: {'expected': 1, 'gridID': 33344},
 33347: {'expected': 1, 'gridID': 33347},
 33350: {'expected': 1, 'gridID': 33350},
 33351: {'expected': 1, 'gridID': 33351},
 33353: {'expected': 3, 'gridID': 33353},
 33356: {'expected': 3, 'gridID': 33356},
 33365: {'expected': 4, 'gridID': 33365},
 33366: {'expected': 2, 'gridID': 33366},
 33367: {'expected': 7, 'gridID': 33367},
 33371: {'expected': 2, 'gridID': 33371},
 33372: {'expected': 5, 'gridID': 33372},
 33373: {'expected': 4, 'gridID': 33373},
 33375: {'expected': 2, 'gridID': 33375},
 33376: {'expected': 5, 'gridID': 33376},
 33377: {'expected': 2, 'gridID': 33377},
 33379: {'expected': 1, 'gridID': 33379},
 33380: {'expected': 5, 'gridID': 33380},
 33381: {'expected': 4, 'gridID': 33381},
 33386: {'expected': 2, 'gridID': 33386},
 33388: {'expected': 3, 'gridID': 33388},
 33389: {'expected': 1, 'gridID': 33389},
 33391: {'expected': 5, 'gridID': 33391},
 33393: {'expected': 3, 'gridID': 33393},
 33396: {'expected': 1, 'gridID': 33396},
 33398: {'expected': 1, 'gridID': 33398},
 33451: {'expected': 6, 'gridID': 33451},
 33455: {'expected': 1, 'gridID': 33455},
 33456: {'expected': 1, 'gridID': 33456},
 33457: {'expected': 2, 'gridID': 33457},
 33458: {'expected': 1, 'gridID': 33458},
 33459: {'expected': 2, 'gridID': 33459},
 33460: {'expected': 1, 'gridID': 33460},
 33461: {'expected': 1, 'gridID': 33461},
 33462: {'expected': 4, 'gridID': 33462},
 33463: {'expected': 3, 'gridID': 33463},
 33464: {'expected': 2, 'gridID': 33464},
 33465: {'expected': 3, 'gridID': 33465},
 33466: {'expected': 6, 'gridID': 33466},
 33467: {'expected': 2, 'gridID': 33467},
 33468: {'expected': 3, 'gridID': 33468},
 33469: {'expected': 4, 'gridID': 33469},
 33470: {'expected': 5, 'gridID': 33470},
 33471: {'expected': 3, 'gridID': 33471},
 33472: {'expected': 4, 'gridID': 33472},
 33474: {'expected': 2, 'gridID': 33474},
 33475: {'expected': 1, 'gridID': 33475},
 33476: {'expected': 4, 'gridID': 33476},
 33483: {'expected': 4, 'gridID': 33483},
 33484: {'expected': 4, 'gridID': 33484},
 33485: {'expected': 1, 'gridID': 33485},
 33486: {'expected': 3, 'gridID': 33486},
 33487: {'expected': 1, 'gridID': 33487},
 33488: {'expected': 3, 'gridID': 33488},
 33489: {'expected': 5, 'gridID': 33489},
 33490: {'expected': 1, 'gridID': 33490},
 33491: {'expected': 4, 'gridID': 33491},
 33493: {'expected': 5, 'gridID': 33493},
 33494: {'expected': 5, 'gridID': 33494},
 33495: {'expected': 3, 'gridID': 33495},
 33496: {'expected': 13, 'gridID': 33496},
 33497: {'expected': 4, 'gridID': 33497},
 33498: {'expected': 6, 'gridID': 33498},
 33499: {'expected': 2, 'gridID': 33499},
 33500: {'expected': 6, 'gridID': 33500},
 33501: {'expected': 9, 'gridID': 33501},
 33528: {'expected': 1, 'gridID': 33528},
 33530: {'expected': 1, 'gridID': 33530},
 33535: {'expected': 1, 'gridID': 33535},
 33542: {'expected': 1, 'gridID': 33542},
 33547: {'expected': 2, 'gridID': 33547},
 33549: {'expected': 1, 'gridID': 33549},
 33570: {'expected': 1, 'gridID': 33570},
 33576: {'expected': 1, 'gridID': 33576},
 33577: {'expected': 4, 'gridID': 33577},
 33579: {'expected': 1, 'gridID': 33579},
 33580: {'expected': 1, 'gridID': 33580},
 33581: {'expected': 1, 'gridID': 33581},
 33582: {'expected': 1, 'gridID': 33582},
 33584: {'expected': 1, 'gridID': 33584},
 33595: {'expected': 1, 'gridID': 33595},
 33596: {'expected': 5, 'gridID': 33596},
 33600: {'expected': 1, 'gridID': 33600},
 33601: {'expected': 10, 'gridID': 33601},
 33604: {'expected': 1, 'gridID': 33604},
 33605: {'expected': 5, 'gridID': 33605},
 33606: {'expected': 2, 'gridID': 33606},
 33609: {'expected': 2, 'gridID': 33609},
 33610: {'expected': 1, 'gridID': 33610},
 33613: {'expected': 1, 'gridID': 33613},
 33617: {'expected': 3, 'gridID': 33617},
 33618: {'expected': 1, 'gridID': 33618},
 33623: {'expected': 1, 'gridID': 33623},
 33624: {'expected': 1, 'gridID': 33624},
 33625: {'expected': 2, 'gridID': 33625},
 33626: {'expected': 4, 'gridID': 33626},
 33679: {'expected': 1, 'gridID': 33679},
 33680: {'expected': 2, 'gridID': 33680},
 33681: {'expected': 1, 'gridID': 33681},
 33683: {'expected': 4, 'gridID': 33683},
 33684: {'expected': 1, 'gridID': 33684},
 33687: {'expected': 1, 'gridID': 33687},
 33688: {'expected': 5, 'gridID': 33688},
 33689: {'expected': 2, 'gridID': 33689},
 33690: {'expected': 3, 'gridID': 33690},
 33691: {'expected': 6, 'gridID': 33691},
 33693: {'expected': 1, 'gridID': 33693},
 33694: {'expected': 5, 'gridID': 33694},
 33695: {'expected': 4, 'gridID': 33695},
 33696: {'expected': 1, 'gridID': 33696},
 33697: {'expected': 3, 'gridID': 33697},
 33698: {'expected': 2, 'gridID': 33698},
 33699: {'expected': 3, 'gridID': 33699},
 33700: {'expected': 9, 'gridID': 33700},
 33701: {'expected': 2, 'gridID': 33701},
 33702: {'expected': 1, 'gridID': 33702},
 33703: {'expected': 2, 'gridID': 33703},
 33704: {'expected': 4, 'gridID': 33704},
 33705: {'expected': 5, 'gridID': 33705},
 33707: {'expected': 1, 'gridID': 33707},
 33708: {'expected': 9, 'gridID': 33708},
 33711: {'expected': 2, 'gridID': 33711},
 33712: {'expected': 6, 'gridID': 33712},
 33715: {'expected': 2, 'gridID': 33715},
 33716: {'expected': 1, 'gridID': 33716},
 33717: {'expected': 4, 'gridID': 33717},
 33718: {'expected': 2, 'gridID': 33718},
 33719: {'expected': 2, 'gridID': 33719},
 33720: {'expected': 1, 'gridID': 33720},
 33722: {'expected': 4, 'gridID': 33722},
 33723: {'expected': 3, 'gridID': 33723},
 33724: {'expected': 4, 'gridID': 33724},
 33725: {'expected': 1, 'gridID': 33725},
 33726: {'expected': 2, 'gridID': 33726},
 33727: {'expected': 1, 'gridID': 33727},
 33728: {'expected': 2, 'gridID': 33728},
 33729: {'expected': 4, 'gridID': 33729},
 33769: {'expected': 1, 'gridID': 33769},
 33774: {'expected': 1, 'gridID': 33774},
 33776: {'expected': 7, 'gridID': 33776},
 33777: {'expected': 1, 'gridID': 33777},
 33779: {'expected': 1, 'gridID': 33779},
 33780: {'expected': 2, 'gridID': 33780},
 33792: {'expected': 1, 'gridID': 33792},
 33798: {'expected': 1, 'gridID': 33798},
 33800: {'expected': 1, 'gridID': 33800},
 33802: {'expected': 1, 'gridID': 33802},
 33803: {'expected': 1, 'gridID': 33803},
 33804: {'expected': 3, 'gridID': 33804},
 33807: {'expected': 2, 'gridID': 33807},
 33808: {'expected': 3, 'gridID': 33808},
 33809: {'expected': 1, 'gridID': 33809},
 33810: {'expected': 4, 'gridID': 33810},
 33811: {'expected': 1, 'gridID': 33811},
 33812: {'expected': 1, 'gridID': 33812},
 33824: {'expected': 4, 'gridID': 33824},
 33825: {'expected': 4, 'gridID': 33825},
 33826: {'expected': 2, 'gridID': 33826},
 33827: {'expected': 3, 'gridID': 33827},
 33830: {'expected': 4, 'gridID': 33830},
 33831: {'expected': 1, 'gridID': 33831},
 33832: {'expected': 1, 'gridID': 33832},
 33833: {'expected': 2, 'gridID': 33833},
 33834: {'expected': 2, 'gridID': 33834},
 33837: {'expected': 4, 'gridID': 33837},
 33838: {'expected': 1, 'gridID': 33838},
 33844: {'expected': 1, 'gridID': 33844},
 33846: {'expected': 1, 'gridID': 33846},
 33847: {'expected': 1, 'gridID': 33847},
 33848: {'expected': 1, 'gridID': 33848},
 33850: {'expected': 1, 'gridID': 33850},
 33851: {'expected': 1, 'gridID': 33851},
 33853: {'expected': 1, 'gridID': 33853},
 33855: {'expected': 2, 'gridID': 33855},
 1103: {'expected': 1, 'gridID': 1103},
 1104: {'expected': 5, 'gridID': 1104},
 1105: {'expected': 1, 'gridID': 1105},
 33894: {'expected': 1, 'gridID': 33894},
 33904: {'expected': 1, 'gridID': 33904},
 33905: {'expected': 2, 'gridID': 33905},
 33909: {'expected': 2, 'gridID': 33909},
 33916: {'expected': 1, 'gridID': 33916},
 33918: {'expected': 2, 'gridID': 33918},
 33919: {'expected': 1, 'gridID': 33919},
 33920: {'expected': 2, 'gridID': 33920},
 33921: {'expected': 9, 'gridID': 33921},
 33923: {'expected': 3, 'gridID': 33923},
 33924: {'expected': 10, 'gridID': 33924},
 33925: {'expected': 4, 'gridID': 33925},
 33926: {'expected': 3, 'gridID': 33926},
 33927: {'expected': 4, 'gridID': 33927},
 33928: {'expected': 7, 'gridID': 33928},
 33929: {'expected': 5, 'gridID': 33929},
 33930: {'expected': 1, 'gridID': 33930},
 33931: {'expected': 4, 'gridID': 33931},
 33938: {'expected': 1, 'gridID': 33938},
 33939: {'expected': 2, 'gridID': 33939},
 33942: {'expected': 1, 'gridID': 33942},
 33943: {'expected': 2, 'gridID': 33943},
 33944: {'expected': 2, 'gridID': 33944},
 33945: {'expected': 2, 'gridID': 33945},
 33947: {'expected': 3, 'gridID': 33947},
 33948: {'expected': 3, 'gridID': 33948},
 33949: {'expected': 1, 'gridID': 33949},
 33951: {'expected': 2, 'gridID': 33951},
 33952: {'expected': 2, 'gridID': 33952},
 33953: {'expected': 1, 'gridID': 33953},
 33954: {'expected': 6, 'gridID': 33954},
 33955: {'expected': 2, 'gridID': 33955},
 33956: {'expected': 5, 'gridID': 33956},
 33957: {'expected': 1, 'gridID': 33957},
 33958: {'expected': 1, 'gridID': 33958},
 33999: {'expected': 1, 'gridID': 33999},
 34000: {'expected': 1, 'gridID': 34000},
 34003: {'expected': 3, 'gridID': 34003},
 34005: {'expected': 3, 'gridID': 34005},
 34008: {'expected': 1, 'gridID': 34008},
 34010: {'expected': 1, 'gridID': 34010},
 34013: {'expected': 1, 'gridID': 34013},
 34016: {'expected': 1, 'gridID': 34016},
 34020: {'expected': 3, 'gridID': 34020},
 34030: {'expected': 1, 'gridID': 34030},
 34031: {'expected': 2, 'gridID': 34031},
 34035: {'expected': 1, 'gridID': 34035},
 34036: {'expected': 1, 'gridID': 34036},
 34037: {'expected': 2, 'gridID': 34037},
 34039: {'expected': 1, 'gridID': 34039},
 34052: {'expected': 1, 'gridID': 34052},
 34053: {'expected': 4, 'gridID': 34053},
 34054: {'expected': 3, 'gridID': 34054},
 34055: {'expected': 2, 'gridID': 34055},
 34059: {'expected': 1, 'gridID': 34059},
 34060: {'expected': 4, 'gridID': 34060},
 34061: {'expected': 3, 'gridID': 34061},
 34062: {'expected': 2, 'gridID': 34062},
 34063: {'expected': 3, 'gridID': 34063},
 34064: {'expected': 6, 'gridID': 34064},
 34065: {'expected': 5, 'gridID': 34065},
 34066: {'expected': 8, 'gridID': 34066},
 34067: {'expected': 3, 'gridID': 34067},
 34068: {'expected': 2, 'gridID': 34068},
 34072: {'expected': 3, 'gridID': 34072},
 34073: {'expected': 4, 'gridID': 34073},
 34074: {'expected': 4, 'gridID': 34074},
 34076: {'expected': 1, 'gridID': 34076},
 34077: {'expected': 1, 'gridID': 34077},
 34078: {'expected': 3, 'gridID': 34078},

In [9]:
df = pd.DataFrame.from_dict(d14, orient='index')
df

       expected  gridID
1103          1    1103
1104          5    1104
1105          1    1105
1333          1    1333
1335          1    1335
1345          1    1345
1348          1    1348
1353          1    1353
1372          6    1372
1567          1    1567
1790          1    1790
1793          1    1793
1794          1    1794
1799          3    1799
2028          4    2028
2052          1    2052
2057          1    2057
2251          1    2251
2254          1    2254
2259          1    2259
2271          1    2271
2288          1    2288
2479          1    2479
2480          1    2480
2481          1    2481
2482          1    2482
2487          1    2487
2709          1    2709
2711          3    2711
2724          1    2724
...         ...     ...
53947         2   53947
53952         1   53952
53985         1   53985
53991         1   53991
53992         2   53992
53994         2   53994
54148         1   54148
54177         1   54177
54182         1   54182
54184         2   54184
54190         1   54190
54196         1   54196
54213         1   54213
54436         1   54436
54440         1   54440
54616         1   54616
54660         1   54660
54858         1   54858
54859         1   54859
55077         1   55077
55082         1   55082
55534         1   55534
55756         1   55756
56000         1   56000
56217         1   56217
56219         1   56219
56682         1   56682
56687         1   56687
57367         1   57367
57369         1   57369

[7309 rows x 2 columns]

In [10]:
df.max()

expected       32
gridID      57369
dtype: int64

In [11]:
grids = pd.read_json('../src/Preprocessing/PlacesData/grids.json')
grids_list = grids[0].tolist()
qs = q[q['gridID'].isin(grids_list)]
qs

             avg  gridID
0      22.279450     196
1      17.950998     197
2      21.120518     198
3      22.734419     199
4      23.235004     200
5      18.710251     201
6      22.085176     202
7      20.430030     203
8      21.608192     204
9      20.098252     205
10     20.083464     206
11     26.821541     207
12     20.884911     208
13     20.499053     209
14     22.762152     210
15     23.123714     215
16     29.468908     216
17     20.943741     426
18     20.505839     427
19     17.873001     428
20     19.557288     429
21     20.052414     430
22     18.368172     431
23     21.413067     432
24     23.169758     433
25     24.908276     434
26     19.140865     435
27     21.811961     436
28     19.663059     437
29     19.538692     438
...          ...     ...
19474  25.615719   53746
19475  28.737615   53747
19476  29.398931   53748
19477  22.200115   53749
19478  25.460827   53750
19479  25.844656   53751
19480  26.589759   53752
19481  23.994577   53753
19482  27.966408   53754
19483  25.279336   53755
19484  26.719218   53966
19485  20.653399   53967
19486  24.477936   53968
19487  24.741840   53969
19488  24.687616   53970
19489  25.241251   53971
19490  26.507545   53972
19491  23.749257   53973
19492  22.082750   53974
19493  25.810196   53975
19494  30.502871   53976
19495  33.106403   53977
19496  33.234264   53978
19497  22.854542   54195
19498  27.912496   54196
19499  24.489921   54197
19500  26.858607   54198
19501  24.078130   54199
19502  24.630159   54200
19503  24.975813   54201

[19443 rows x 2 columns]

In [12]:
dfqs = df.merge(qs, how='right', on='gridID')

In [13]:
dfqs

       expected   gridID        avg
0           1.0   1103.0  21.606264
1           5.0   1104.0  22.405829
2           1.0   1105.0  24.368905
3           1.0   1333.0  21.122838
4           1.0   1335.0  23.366057
5           1.0   1345.0  21.572577
6           1.0   1348.0  23.019797
7           1.0   1353.0  25.068540
8           6.0   1372.0  22.417475
9           1.0   1567.0  24.657417
10          1.0   1790.0  21.538376
11          1.0   1793.0  21.157133
12          1.0   1794.0  21.172905
13          3.0   1799.0  17.322866
14          4.0   2028.0  17.923563
15          1.0   2052.0  21.452463
16          1.0   2057.0  22.916991
17          1.0   2251.0  23.439030
18          1.0   2254.0  21.977568
19          1.0   2259.0  23.427312
20          1.0   2271.0  20.841903
21          1.0   2288.0  23.263982
22          1.0   2479.0  19.957898
23          1.0   2480.0  22.316002
24          1.0   2481.0  21.367030
25          1.0   2482.0  21.611502
26          1.0   2487.0  24.245057
27          1.0   2709.0  21.897431
28          3.0   2711.0  21.307136
29          1.0   2724.0  24.271884
...         ...      ...        ...
19413       NaN  53743.0  26.107289
19414       NaN  53744.0  23.326639
19415       NaN  53745.0  25.776544
19416       NaN  53746.0  25.615719
19417       NaN  53747.0  28.737615
19418       NaN  53748.0  29.398931
19419       NaN  53749.0  22.200115
19420       NaN  53750.0  25.460827
19421       NaN  53751.0  25.844656
19422       NaN  53752.0  26.589759
19423       NaN  53753.0  23.994577
19424       NaN  53966.0  26.719218
19425       NaN  53967.0  20.653399
19426       NaN  53968.0  24.477936
19427       NaN  53969.0  24.741840
19428       NaN  53970.0  24.687616
19429       NaN  53971.0  25.241251
19430       NaN  53972.0  26.507545
19431       NaN  53973.0  23.749257
19432       NaN  53974.0  22.082750
19433       NaN  53975.0  25.810196
19434       NaN  53976.0  30.502871
19435       NaN  53977.0  33.106403
19436       NaN  53978.0  33.234264
19437       NaN  54195.0  22.854542
19438       NaN  54197.0  24.489921
19439       NaN  54198.0  26.858607
19440       NaN  54199.0  24.078130
19441       NaN  54200.0  24.630159
19442       NaN  54201.0  24.975813

[19443 rows x 3 columns]

In [14]:
dfqs.fillna(value='0', inplace=True)
dfqs

      expected   gridID        avg
0            1   1103.0  21.606264
1            5   1104.0  22.405829
2            1   1105.0  24.368905
3            1   1333.0  21.122838
4            1   1335.0  23.366057
5            1   1345.0  21.572577
6            1   1348.0  23.019797
7            1   1353.0  25.068540
8            6   1372.0  22.417475
9            1   1567.0  24.657417
10           1   1790.0  21.538376
11           1   1793.0  21.157133
12           1   1794.0  21.172905
13           3   1799.0  17.322866
14           4   2028.0  17.923563
15           1   2052.0  21.452463
16           1   2057.0  22.916991
17           1   2251.0  23.439030
18           1   2254.0  21.977568
19           1   2259.0  23.427312
20           1   2271.0  20.841903
21           1   2288.0  23.263982
22           1   2479.0  19.957898
23           1   2480.0  22.316002
24           1   2481.0  21.367030
25           1   2482.0  21.611502
26           1   2487.0  24.245057
27           1   2709.0  21.897431
28           3   2711.0  21.307136
29           1   2724.0  24.271884
...        ...      ...        ...
19413        0  53743.0  26.107289
19414        0  53744.0  23.326639
19415        0  53745.0  25.776544
19416        0  53746.0  25.615719
19417        0  53747.0  28.737615
19418        0  53748.0  29.398931
19419        0  53749.0  22.200115
19420        0  53750.0  25.460827
19421        0  53751.0  25.844656
19422        0  53752.0  26.589759
19423        0  53753.0  23.994577
19424        0  53966.0  26.719218
19425        0  53967.0  20.653399
19426        0  53968.0  24.477936
19427        0  53969.0  24.741840
19428        0  53970.0  24.687616
19429        0  53971.0  25.241251
19430        0  53972.0  26.507545
19431        0  53973.0  23.749257
19432        0  53974.0  22.082750
19433        0  53975.0  25.810196
19434        0  53976.0  30.502871
19435        0  53977.0  33.106403
19436        0  53978.0  33.234264
19437        0  54195.0  22.854542
19438        0  54197.0  24.489921
19439        0  54198.0  26.858607
19440        0  54199.0  24.078130
19441        0  54200.0  24.630159
19442        0  54201.0  24.975813

[19443 rows x 3 columns]

In [16]:
from ggplot import *

In [154]:
ss = ggplot(dfqs, aes('expected', 'avg')) + \
    geom_point() + \
    theme(axis_text=element_text(size=12, family='serif')) + \
    xlab(element_text(text='Robberies in 2014', size=14, family='serif')) + \
    ylab(element_text(text='Q-score', size=14, family='serif'))

In [155]:
ss.save('./graphs/qs.png')

In [83]:
ss.save('./ss2.png')

In [71]:
len(dfqs['expected'].tolist())

# len(dfqs['avg'].tolist())

19443

In [86]:
dfqs['avg'].std()

3.5590328795171438

In [65]:
scipy.stats.pearsonr(dfqs['expected'].tolist(), dfqs['avg'].tolist())

TypeError: cannot perform reduce with flexible type

In [67]:
from patsy import dmatrices

In [79]:
y, X = dmatrices('expected ~ avg', data=dfqs, return_type='dataframe')

In [80]:
import statsmodels.api as sm

mod = sm.OLS(y, X)
res = mod.fit()

In [19]:
dfqs['est'] = 0

In [73]:
res.summary()

ValueError: shapes (19443,20) and (19443,20) not aligned: 20 (dim 1) != 19443 (dim 0)

In [28]:
dfqs

      expected   gridID        avg  est
0            1   1103.0  21.606264    0
1            5   1104.0  22.405829    0
2            1   1105.0  24.368905    0
3            1   1333.0  21.122838    0
4            1   1335.0  23.366057    0
5            1   1345.0  21.572577    0
6            1   1348.0  23.019797    0
7            1   1353.0  25.068540    0
8            6   1372.0  22.417475    0
9            1   1567.0  24.657417    0
10           1   1790.0  21.538376    0
11           1   1793.0  21.157133    0
12           1   1794.0  21.172905    0
13           3   1799.0  17.322866    0
14           4   2028.0  17.923563    0
15           1   2052.0  21.452463    0
16           1   2057.0  22.916991    0
17           1   2251.0  23.439030    0
18           1   2254.0  21.977568    0
19           1   2259.0  23.427312    0
20           1   2271.0  20.841903    0
21           1   2288.0  23.263982    0
22           1   2479.0  19.957898    0
23           1   2480.0  22.316002    0
24           1   2481.0  21.367030    0
25           1   2482.0  21.611502    0
26           1   2487.0  24.245057    0
27           1   2709.0  21.897431    0
28           3   2711.0  21.307136    0
29           1   2724.0  24.271884    0
...        ...      ...        ...  ...
19413        0  53743.0  26.107289    0
19414        0  53744.0  23.326639    0
19415        0  53745.0  25.776544    0
19416        0  53746.0  25.615719    0
19417        0  53747.0  28.737615    0
19418        0  53748.0  29.398931    0
19419        0  53749.0  22.200115    0
19420        0  53750.0  25.460827    0
19421        0  53751.0  25.844656    0
19422        0  53752.0  26.589759    0
19423        0  53753.0  23.994577    0
19424        0  53966.0  26.719218    0
19425        0  53967.0  20.653399    0
19426        0  53968.0  24.477936    0
19427        0  53969.0  24.741840    0
19428        0  53970.0  24.687616    0
19429        0  53971.0  25.241251    0
19430        0  53972.0  26.507545    0
19431        0  53973.0  23.749257    0
19432        0  53974.0  22.082750    0
19433        0  53975.0  25.810196    0
19434        0  53976.0  30.502871    0
19435        0  53977.0  33.106403    0
19436        0  53978.0  33.234264    0
19437        0  54195.0  22.854542    0
19438        0  54197.0  24.489921    0
19439        0  54198.0  26.858607    0
19440        0  54199.0  24.078130    0
19441        0  54200.0  24.630159    0
19442        0  54201.0  24.975813    0

[19443 rows x 4 columns]

In [20]:
places = pd.read_csv('Places.csv')
places

,Unnamed: 0,center,gridID,num_establishments,num_liquor_stores,num_restaurants,num_stores,num_bars
0,0,"[40.58126700435262, -73.88885569258588]",35265,0,0,0,0,0
1,1,"[40.58126700435262, -73.88696208494963]",35494,0,0,0,0,0
2,2,"[40.58126700435262, -73.88506847731342]",35723,0,0,0,0,0
3,3,"[40.58270515366833, -73.88885569258588]",35264,0,0,0,0,0
4,4,"[40.58270515366833, -73.88696208494963]",35493,0,0,0,0,0
5,5,"[40.58270515366833, -73.88506847731342]",35722,0,0,0,0,0
6,6,"[40.58126700435262, -73.88317486967719]",35952,1,0,0,0,0
7,7,"[40.58270515366833, -73.88317486967719]",35951,0,0,0,0,0
8,8,"[40.58270515366833, -73.88128126204097]",36180,1,0,0,0,0
9,9,"[40.58270515366833, -73.87938765440474]",36409,0,0,0,0,0
10,10,"[40.58126700435262, -73.87938765440474]",36410,0,0,0,0,0
11,11,"[40.58126700435262, -73.88128126204097]",36181,0,0,0,0,0
12,12,"[40.58126700435262, -73.8774940467685]",36639,0,0,0,0,0
13,13,"[40.58126700435262, -73.87560043913228]",36868,0,0,0,0,0
14,14,"[40.58126700435262, -73.87370683149605]",37097,0,0,0,0,0
15,15,"[40.58126700435262, -73.87181322385982]",37326,0,0,0,0,0
16,16,"[40.58126700435262, -73.86991961622361]",37555,0,0,0,0,0
17,17,"[40.58126700435262, -73.86802600858738]",37784,0,0,0,0,0
18,18,"[40.58126700435262, -73.84530271695266]",40532,5,0,0,0,0
19,19,"[40.58126700435262, -73.84719632458888]",40303,6,0,0,0,0
20,20,"[40.58270515366833, -73.84719632458888]",40302,0,0,0,0,0
21,21,"[40.58270515366833, -73.84530271695266]",40531,0,0,0,0,0
22,22,"[40.58270515366833, -73.84340910931643]",40760,0,0,0,0,0
23,23,"[40.58126700435262, -73.84340910931643]",40761,10,0,0,0,0
24,24,"[40.58126700435262, -73.84151550168019]",40990,6,0,0,1,0
25,25,"[40.58270515366833, -73.84151550168019]",40989,0,0,0,0,0
26,26,"[40.58414327206371, -73.84530271695266]",40530,0,0,0,0,0
27,27,"[40.58414327206371, -73.84340910931643]",40759,0,0,0,0,0
28,28,"[40.58414327206371, -73.84151550168019]",40988,0,0,0,0,0
29,29,"[40.585581359538565, -73.84151550168019]",40987,0,0,0,0,0
...,...,...,...,...,...,...,...,...
33374,33374,"[40.85825665065568, -73.94187670640022]",28660,0,0,0,0,0
33375,33375,"[40.85825665065568, -73.93998309876399]",28889,0,0,0,0,0
33376,33376,"[40.856824442368534, -73.93808949112776]",29119,15,0,0,1,0
33377,33377,"[40.856824442368534, -73.93998309876399]",28890,0,0,0,0,0
33378,33378,"[40.85539220311651, -73.93998309876399]",28891,9,0,0,0,0
33379,33379,"[40.85539220311651, -73.93808949112776]",29120,76,1,10,9,3
33380,33380,"[40.8539599328998, -73.93998309876399]",28892,24,0,0,1,0
33381,33381,"[40.8539599328998, -73.93808949112776]",29121,34,0,0,2,0
33382,33382,"[40.85968882797772, -73.93808949112776]",29117,0,0,0,0,0
33383,33383,"[40.85825665065568, -73.93808949112776]",29118,1,0,0,0,0
33384,33384,"[40.85968882797772, -73.94187670640022]",28659,0,0,0,0,0
33385,33385,"[40.85968882797772, -73.93998309876399]",28888,0,0,0,0,0
33386,33386,"[40.8611209743344, -73.93808949112776]",29116,0,0,0,0,0
33387,33387,"[40.8611209743344, -73.94187670640022]",28658,0,0,0,0,0
33388,33388,"[40.8611209743344, -73.93998309876399]",28887,0,0,0,0,0
33389,33389,"[40.86255308972552, -73.94187670640022]",28657,0,0,0,0,0
33390,33390,"[40.86255308972552, -73.93998309876399]",28886,0,0,0,0,0
33391,33391,"[40.86255308972552, -73.93808949112776]",29115,0,0,0,0,0
33392,33392,"[40.863985174150855, -73.93808949112776]",29114,0,0,0,0,0
33393,33393,"[40.86541722761016, -73.93808949112776]",29113,0,0,0,0,0
33394,33394,"[40.86541722761016, -73.93998309876399]",28884,0,0,0,0,0
33395,33395,"[40.86541722761016, -73.94187670640022]",28655,0,0,0,0,0
33396,33396,"[40.863985174150855, -73.94187670640022]",28656,0,0,0,0,0
33397,33397,"[40.863985174150855, -73.93998309876399]",28885,0,0,0,0,0
33398,33398,"[40.86255308972552, -73.94377031403644]",28428,0,0,0,0,0
33399,33399,"[40.8611209743344, -73.94377031403644]",28429,0,0,0,0,0
33400,33400,"[40.85968882797772, -73.94566392167268]",28201,0,0,0,0,0
33401,33401,"[40.85968882797772, -73.94377031403644]",28430,0,0,0,0,0
33402,33402,"[40.852527631718644, -73.94945113694513]",27748,0,0,0,0,0
33403,33403,"[40.85109529957329, -73.94945113694513]",27749,0,0,0,0,0

In [31]:
#match number of establishments to this:
for i, r in dfqs.iterrows():
    row = places.loc[places['gridID'] == r['gridID']]
    dfqs.loc[i, 'est'] = row['num_establishments']

ValueError: Incompatible indexer with Series

In [22]:
dfqs

      expected   gridID        avg  est
0            1   1103.0  21.606264    0
1            5   1104.0  22.405829    0
2            1   1105.0  24.368905    0
3            1   1333.0  21.122838    0
4            1   1335.0  23.366057    0
5            1   1345.0  21.572577    0
6            1   1348.0  23.019797    0
7            1   1353.0  25.068540    0
8            6   1372.0  22.417475    0
9            1   1567.0  24.657417    0
10           1   1790.0  21.538376    0
11           1   1793.0  21.157133    0
12           1   1794.0  21.172905    0
13           3   1799.0  17.322866    0
14           4   2028.0  17.923563    0
15           1   2052.0  21.452463    0
16           1   2057.0  22.916991    0
17           1   2251.0  23.439030    0
18           1   2254.0  21.977568    0
19           1   2259.0  23.427312    0
20           1   2271.0  20.841903    0
21           1   2288.0  23.263982    0
22           1   2479.0  19.957898    0
23           1   2480.0  22.316002    0
24           1   2481.0  21.367030    0
25           1   2482.0  21.611502    0
26           1   2487.0  24.245057    0
27           1   2709.0  21.897431    0
28           3   2711.0  21.307136    0
29           1   2724.0  24.271884    0
...        ...      ...        ...  ...
19413        0  53743.0  26.107289    0
19414        0  53744.0  23.326639    0
19415        0  53745.0  25.776544    0
19416        0  53746.0  25.615719    0
19417        0  53747.0  28.737615    0
19418        0  53748.0  29.398931    0
19419        0  53749.0  22.200115    0
19420        0  53750.0  25.460827    0
19421        0  53751.0  25.844656    0
19422        0  53752.0  26.589759    0
19423        0  53753.0  23.994577    0
19424        0  53966.0  26.719218    0
19425        0  53967.0  20.653399    0
19426        0  53968.0  24.477936    0
19427        0  53969.0  24.741840    0
19428        0  53970.0  24.687616    0
19429        0  53971.0  25.241251    0
19430        0  53972.0  26.507545    0
19431        0  53973.0  23.749257    0
19432        0  53974.0  22.082750    0
19433        0  53975.0  25.810196    0
19434        0  53976.0  30.502871    0
19435        0  53977.0  33.106403    0
19436        0  53978.0  33.234264    0
19437        0  54195.0  22.854542    0
19438        0  54197.0  24.489921    0
19439        0  54198.0  26.858607    0
19440        0  54199.0  24.078130    0
19441        0  54200.0  24.630159    0
19442        0  54201.0  24.975813    0

[19443 rows x 4 columns]

In [127]:
places = pd.read_csv('Places.csv')

In [128]:
dfplaces = places.merge(df, how='outer', on='gridID')

In [129]:
dfplaces

,Unnamed: 0,center,gridID,num_establishments,num_liquor_stores,num_restaurants,num_stores,num_bars,expected
0,0,"[40.58126700435262, -73.88885569258588]",35265,0,0,0,0,0,NaN
1,1,"[40.58126700435262, -73.88696208494963]",35494,0,0,0,0,0,NaN
2,2,"[40.58126700435262, -73.88506847731342]",35723,0,0,0,0,0,NaN
3,3,"[40.58270515366833, -73.88885569258588]",35264,0,0,0,0,0,NaN
4,4,"[40.58270515366833, -73.88696208494963]",35493,0,0,0,0,0,NaN
5,5,"[40.58270515366833, -73.88506847731342]",35722,0,0,0,0,0,NaN
6,6,"[40.58126700435262, -73.88317486967719]",35952,1,0,0,0,0,NaN
7,7,"[40.58270515366833, -73.88317486967719]",35951,0,0,0,0,0,NaN
8,8,"[40.58270515366833, -73.88128126204097]",36180,1,0,0,0,0,NaN
9,9,"[40.58270515366833, -73.87938765440474]",36409,0,0,0,0,0,NaN
10,10,"[40.58126700435262, -73.87938765440474]",36410,0,0,0,0,0,NaN
11,11,"[40.58126700435262, -73.88128126204097]",36181,0,0,0,0,0,NaN
12,12,"[40.58126700435262, -73.8774940467685]",36639,0,0,0,0,0,NaN
13,13,"[40.58126700435262, -73.87560043913228]",36868,0,0,0,0,0,NaN
14,14,"[40.58126700435262, -73.87370683149605]",37097,0,0,0,0,0,NaN
15,15,"[40.58126700435262, -73.87181322385982]",37326,0,0,0,0,0,NaN
16,16,"[40.58126700435262, -73.86991961622361]",37555,0,0,0,0,0,NaN
17,17,"[40.58126700435262, -73.86802600858738]",37784,0,0,0,0,0,NaN
18,18,"[40.58126700435262, -73.84530271695266]",40532,5,0,0,0,0,NaN
19,19,"[40.58126700435262, -73.84719632458888]",40303,6,0,0,0,0,NaN
20,20,"[40.58270515366833, -73.84719632458888]",40302,0,0,0,0,0,NaN
21,21,"[40.58270515366833, -73.84530271695266]",40531,0,0,0,0,0,NaN
22,22,"[40.58270515366833, -73.84340910931643]",40760,0,0,0,0,0,NaN
23,23,"[40.58126700435262, -73.84340910931643]",40761,10,0,0,0,0,NaN
24,24,"[40.58126700435262, -73.84151550168019]",40990,6,0,0,1,0,NaN
25,25,"[40.58270515366833, -73.84151550168019]",40989,0,0,0,0,0,NaN
26,26,"[40.58414327206371, -73.84530271695266]",40530,0,0,0,0,0,NaN
27,27,"[40.58414327206371, -73.84340910931643]",40759,0,0,0,0,0,NaN
28,28,"[40.58414327206371, -73.84151550168019]",40988,0,0,0,0,0,NaN
29,29,"[40.585581359538565, -73.84151550168019]",40987,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...
33374,33374,"[40.85825665065568, -73.94187670640022]",28660,0,0,0,0,0,NaN
33375,33375,"[40.85825665065568, -73.93998309876399]",28889,0,0,0,0,0,NaN
33376,33376,"[40.856824442368534, -73.93808949112776]",29119,15,0,0,1,0,NaN
33377,33377,"[40.856824442368534, -73.93998309876399]",28890,0,0,0,0,0,NaN
33378,33378,"[40.85539220311651, -73.93998309876399]",28891,9,0,0,0,0,NaN
33379,33379,"[40.85539220311651, -73.93808949112776]",29120,76,1,10,9,3,NaN
33380,33380,"[40.8539599328998, -73.93998309876399]",28892,24,0,0,1,0,NaN
33381,33381,"[40.8539599328998, -73.93808949112776]",29121,34,0,0,2,0,NaN
33382,33382,"[40.85968882797772, -73.93808949112776]",29117,0,0,0,0,0,NaN
33383,33383,"[40.85825665065568, -73.93808949112776]",29118,1,0,0,0,0,NaN
33384,33384,"[40.85968882797772, -73.94187670640022]",28659,0,0,0,0,0,NaN
33385,33385,"[40.85968882797772, -73.93998309876399]",28888,0,0,0,0,0,NaN
33386,33386,"[40.8611209743344, -73.93808949112776]",29116,0,0,0,0,0,NaN
33387,33387,"[40.8611209743344, -73.94187670640022]",28658,0,0,0,0,0,NaN
33388,33388,"[40.8611209743344, -73.93998309876399]",28887,0,0,0,0,0,NaN
33389,33389,"[40.86255308972552, -73.94187670640022]",28657,0,0,0,0,0,NaN
33390,33390,"[40.86255308972552, -73.93998309876399]",28886,0,0,0,0,0,NaN
33391,33391,"[40.86255308972552, -73.93808949112776]",29115,0,0,0,0,0,NaN
33392,33392,"[40.863985174150855, -73.93808949112776]",29114,0,0,0,0,0,NaN
33393,33393,"[40.86541722761016, -73.93808949112776]",29113,0,0,0,0,0,NaN
33394,33394,"[40.86541722761016, -73.93998309876399]",28884,0,0,0,0,0,NaN
33395,33395,"[40.86541722761016, -73.94187670640022]",28655,0,0,0,0,0,NaN
33396,33396,"[40.863985174150855, -73.94187670640022]",28656,0,0,0,0,0,NaN
33397,33397,"[40.863985174150855, -73.93998309876399]",28885,0,0,0,0,0,NaN
33398,33398,"[40.86255308972552, -73.94377031403644]",28428,0,0,0,0,0,NaN
33399,33399,"[40.8611209743344, -73.94377031403644]",28429,0,0,0,0,0,NaN
33400,33400,"[40.85968882797772, -73.94566392167268]",28201,0,0,0,0,0,NaN
33401,33401,"[40.85968882797772, -73.94377031403644]",28430,0,0,0,0,0,NaN
33402,33402,"[40.852527631718644, -73.94945113694513]",27748,0,0,0,0,0,NaN
33403,33403,"[40.85109529957329, -73.94945113694513]",27749,0,0,0,0,0,NaN

In [131]:
dfplaces.fillna(value='0', inplace=True)
dfplaces

,Unnamed: 0,center,gridID,num_establishments,num_liquor_stores,num_restaurants,num_stores,num_bars,expected
0,0,"[40.58126700435262, -73.88885569258588]",35265,0,0,0,0,0,0
1,1,"[40.58126700435262, -73.88696208494963]",35494,0,0,0,0,0,0
2,2,"[40.58126700435262, -73.88506847731342]",35723,0,0,0,0,0,0
3,3,"[40.58270515366833, -73.88885569258588]",35264,0,0,0,0,0,0
4,4,"[40.58270515366833, -73.88696208494963]",35493,0,0,0,0,0,0
5,5,"[40.58270515366833, -73.88506847731342]",35722,0,0,0,0,0,0
6,6,"[40.58126700435262, -73.88317486967719]",35952,1,0,0,0,0,0
7,7,"[40.58270515366833, -73.88317486967719]",35951,0,0,0,0,0,0
8,8,"[40.58270515366833, -73.88128126204097]",36180,1,0,0,0,0,0
9,9,"[40.58270515366833, -73.87938765440474]",36409,0,0,0,0,0,0
10,10,"[40.58126700435262, -73.87938765440474]",36410,0,0,0,0,0,0
11,11,"[40.58126700435262, -73.88128126204097]",36181,0,0,0,0,0,0
12,12,"[40.58126700435262, -73.8774940467685]",36639,0,0,0,0,0,0
13,13,"[40.58126700435262, -73.87560043913228]",36868,0,0,0,0,0,0
14,14,"[40.58126700435262, -73.87370683149605]",37097,0,0,0,0,0,0
15,15,"[40.58126700435262, -73.87181322385982]",37326,0,0,0,0,0,0
16,16,"[40.58126700435262, -73.86991961622361]",37555,0,0,0,0,0,0
17,17,"[40.58126700435262, -73.86802600858738]",37784,0,0,0,0,0,0
18,18,"[40.58126700435262, -73.84530271695266]",40532,5,0,0,0,0,0
19,19,"[40.58126700435262, -73.84719632458888]",40303,6,0,0,0,0,0
20,20,"[40.58270515366833, -73.84719632458888]",40302,0,0,0,0,0,0
21,21,"[40.58270515366833, -73.84530271695266]",40531,0,0,0,0,0,0
22,22,"[40.58270515366833, -73.84340910931643]",40760,0,0,0,0,0,0
23,23,"[40.58126700435262, -73.84340910931643]",40761,10,0,0,0,0,0
24,24,"[40.58126700435262, -73.84151550168019]",40990,6,0,0,1,0,0
25,25,"[40.58270515366833, -73.84151550168019]",40989,0,0,0,0,0,0
26,26,"[40.58414327206371, -73.84530271695266]",40530,0,0,0,0,0,0
27,27,"[40.58414327206371, -73.84340910931643]",40759,0,0,0,0,0,0
28,28,"[40.58414327206371, -73.84151550168019]",40988,0,0,0,0,0,0
29,29,"[40.585581359538565, -73.84151550168019]",40987,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
33374,33374,"[40.85825665065568, -73.94187670640022]",28660,0,0,0,0,0,0
33375,33375,"[40.85825665065568, -73.93998309876399]",28889,0,0,0,0,0,0
33376,33376,"[40.856824442368534, -73.93808949112776]",29119,15,0,0,1,0,0
33377,33377,"[40.856824442368534, -73.93998309876399]",28890,0,0,0,0,0,0
33378,33378,"[40.85539220311651, -73.93998309876399]",28891,9,0,0,0,0,0
33379,33379,"[40.85539220311651, -73.93808949112776]",29120,76,1,10,9,3,0
33380,33380,"[40.8539599328998, -73.93998309876399]",28892,24,0,0,1,0,0
33381,33381,"[40.8539599328998, -73.93808949112776]",29121,34,0,0,2,0,0
33382,33382,"[40.85968882797772, -73.93808949112776]",29117,0,0,0,0,0,0
33383,33383,"[40.85825665065568, -73.93808949112776]",29118,1,0,0,0,0,0
33384,33384,"[40.85968882797772, -73.94187670640022]",28659,0,0,0,0,0,0
33385,33385,"[40.85968882797772, -73.93998309876399]",28888,0,0,0,0,0,0
33386,33386,"[40.8611209743344, -73.93808949112776]",29116,0,0,0,0,0,0
33387,33387,"[40.8611209743344, -73.94187670640022]",28658,0,0,0,0,0,0
33388,33388,"[40.8611209743344, -73.93998309876399]",28887,0,0,0,0,0,0
33389,33389,"[40.86255308972552, -73.94187670640022]",28657,0,0,0,0,0,0
33390,33390,"[40.86255308972552, -73.93998309876399]",28886,0,0,0,0,0,0
33391,33391,"[40.86255308972552, -73.93808949112776]",29115,0,0,0,0,0,0
33392,33392,"[40.863985174150855, -73.93808949112776]",29114,0,0,0,0,0,0
33393,33393,"[40.86541722761016, -73.93808949112776]",29113,0,0,0,0,0,0
33394,33394,"[40.86541722761016, -73.93998309876399]",28884,0,0,0,0,0,0
33395,33395,"[40.86541722761016, -73.94187670640022]",28655,0,0,0,0,0,0
33396,33396,"[40.863985174150855, -73.94187670640022]",28656,0,0,0,0,0,0
33397,33397,"[40.863985174150855, -73.93998309876399]",28885,0,0,0,0,0,0
33398,33398,"[40.86255308972552, -73.94377031403644]",28428,0,0,0,0,0,0
33399,33399,"[40.8611209743344, -73.94377031403644]",28429,0,0,0,0,0,0
33400,33400,"[40.85968882797772, -73.94566392167268]",28201,0,0,0,0,0,0
33401,33401,"[40.85968882797772, -73.94377031403644]",28430,0,0,0,0,0,0
33402,33402,"[40.852527631718644, -73.94945113694513]",27748,0,0,0,0,0,0
33403,33403,"[40.85109529957329, -73.94945113694513]",27749,0,0,0,0,0,0

In [152]:
est = ggplot(dfplaces, aes('expected', 'num_bars')) + \
    geom_point() + \
    theme(axis_text=element_text(size=12, family='serif')) + \
    xlab(element_text(text='Robberies in 2014', size=14, family='serif')) + \
    ylab(element_text(text='Number of Bars', size=14, family='serif'))

In [153]:
est.save('bars.jpg')